[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "tm-utilities"
version = "0.1.0"
description = "TM Utilities"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pymongo>=4.17.0",
    "pyodbc>=5.3.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
